"""add c2pa columns to evidence_items

Revision ID: 64ea7c8376d3
Revises: 43b9deb3ef2e
Create Date: 2026-05-22 14:23:56.191304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ea7c8376d3'
down_revision: Union[str, Sequence[str], None] = '43b9deb3ef2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_items', sa.Column('c2pa_state', sa.String(length=20), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_has_ai_generation', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('evidence_items', sa.Column('c2pa_has_ai_modification', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('evidence_items', sa.Column('c2pa_signature_valid', sa.Boolean(), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_claim_generator', sa.String(length=255), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_signature_issuer', sa.String(length=255), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_signature_time', sa.String(length=50), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_plain_english', sa.Text(), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_items', 'c2pa_analyzed_at')
    op.drop_column('evidence_items', 'c2pa_plain_english')
    op.drop_column('evidence_items', 'c2pa_signature_time')
    op.drop_column('evidence_items', 'c2pa_signature_issuer')
    op.drop_column('evidence_items', 'c2pa_claim_generator')
    op.drop_column('evidence_items', 'c2pa_signature_valid')
    op.drop_column('evidence_items', 'c2pa_has_ai_modification')
    op.drop_column('evidence_items', 'c2pa_has_ai_generation')
    op.drop_column('evidence_items', 'c2pa_state')
    # ### end Alembic commands ###
