"""drop redundant ix_payments_stripe_event_id index

Revision ID: 952f89979ed5
Revises: f1a1c24596d4
Create Date: 2026-05-23 06:59:49.718302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952f89979ed5'
down_revision: Union[str, Sequence[str], None] = 'f1a1c24596d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_event_id'), table_name='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payments_stripe_event_id'), 'payments', ['stripe_event_id'], unique=False)
    # ### end Alembic commands ###
