"""add cookie_consent_at and cookie_consent_version to users

Revision ID: a7660954672a
Revises: 952f89979ed5
Create Date: 2026-05-23 10:21:41.155737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7660954672a'
down_revision: Union[str, Sequence[str], None] = '952f89979ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cookie_consent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('cookie_consent_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cookie_consent_version')
    op.drop_column('users', 'cookie_consent_at')
    # ### end Alembic commands ###
