"""add remaining c2pa columns and nullable ai booleans

Revision ID: f1a1c24596d4
Revises: 64ea7c8376d3
Create Date: 2026-05-22 17:12:30.438485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a1c24596d4'
down_revision: Union[str, Sequence[str], None] = '64ea7c8376d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_items', sa.Column('c2pa_claim_generator_version', sa.String(length=100), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_num_assertions', sa.Integer(), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_num_ingredients', sa.Integer(), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_trust_list_status', sa.String(length=50), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_revocation_status', sa.String(length=50), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_ai_agents_found', sa.JSON(), nullable=True))
    op.add_column('evidence_items', sa.Column('c2pa_has_training_mining', sa.Boolean(), nullable=True))
    op.alter_column('evidence_items', 'c2pa_has_ai_generation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('evidence_items', 'c2pa_has_ai_modification',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence_items', 'c2pa_has_ai_modification',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('evidence_items', 'c2pa_has_ai_generation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('evidence_items', 'c2pa_has_training_mining')
    op.drop_column('evidence_items', 'c2pa_ai_agents_found')
    op.drop_column('evidence_items', 'c2pa_revocation_status')
    op.drop_column('evidence_items', 'c2pa_trust_list_status')
    op.drop_column('evidence_items', 'c2pa_num_ingredients')
    op.drop_column('evidence_items', 'c2pa_num_assertions')
    op.drop_column('evidence_items', 'c2pa_claim_generator_version')
    # ### end Alembic commands ###
