import io
import os
import tempfile
import uuid
from datetime import datetime, timezone

import qrcode
from reportlab.lib.units import inch
from reportlab.platypus import Image, KeepTogether, Paragraph, Spacer, Table, TableStyle

from app.pdf_base import (
    DARK, GREY_LINE, PURPLE, PURPLE_BG, WHITE,
    build_document, build_metadata_table, build_styles, hr, section_spacer,
)
from app.utils.map_render import render_map_png
from app.utils.geocode import reverse_geocode


# =========================================================
# HELPERS
# =========================================================

def _redact_email(email: str) -> str:
    """k***@caldwell-law-firm.com"""
    if not email or "@" not in email:
        return email or "—"
    local, domain = email.split("@", 1)
    return f"{local[0]}***@{domain}"


def _fmt_bytes(size_bytes) -> str:
    try:
        b = int(size_bytes)
        if b < 1024:
            return f"{b} bytes"
        elif b < 1024 ** 2:
            return f"{b / 1024:.1f} KB"
        else:
            return f"{b / 1024 ** 2:.1f} MB"
    except Exception:
        return str(size_bytes)


def _generate_qr(url: str) -> Image:
    qr = qrcode.QRCode(box_size=4, border=2)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return Image(buf, width=1.2 * inch, height=1.2 * inch)


# =========================================================
# MAIN GENERATOR
# =========================================================

def generate_integrity_certificate(
    report: dict,
    case_id: str,
    evidence_id: str,
    generated_by: str,
    base_url: str = "https://evidenceanalyzer.com",
    chain_verified: bool = None,
) -> tuple:
    """
    Generates the Integrity Certificate PDF.

    Returns:
        (certificate_id, pdf_bytes)
        certificate_id: UUID v4 string
        pdf_bytes: bytes of the generated PDF
    """
    certificate_id = str(uuid.uuid4())
    generated_at = datetime.now(timezone.utc)
    generated_at_str = generated_at.strftime("%B %d, %Y at %H:%M:%S UTC")
    verify_url = f"{base_url}/verify/{certificate_id}"

    styles = build_styles()
    content = []

    # ── SECTION 1: HEADER ─────────────────────────────────
    content.append(Paragraph("Evidentix\u2122 Integrity Certificate", styles["title"]))
    content.append(Paragraph("Cryptographic Verification of File Integrity", styles["subtitle"]))
    content.append(hr(styles))

    header_rows = [
        ("Generated By",    "Evidentix\u2122 | Evidence Analyzer, LLC"),
        ("Generated",       generated_at_str),
        ("Certificate ID",  certificate_id),
        ("For use in",      f"Case {case_id}"),
  
    ]
    content.append(build_metadata_table(header_rows))
    content.append(section_spacer())

    # File metadata table
    file_name   = report.get("file_name", "—")
    file_size   = _fmt_bytes(report.get("file_size"))
    mime_type   = report.get("metadata", {}).get("mime_type") or report.get("metadata", {}).get("format") or "—"
    upload_date = report.get("analysis_date", "—")
    sha256      = report.get("sha256", "—")
    redacted_user = _redact_email(generated_by)

    file_rows = [
        ("File Name",       file_name),
        ("File Size",       file_size),
        ("File Type",       mime_type),
        ("Upload Date",     upload_date),
        ("Uploading User",  redacted_user),
        ("SHA-256 Hash",    sha256),
    ]
    content.append(Paragraph("File Information", styles["h2"]))
    content.append(build_metadata_table(file_rows))

    # One-sentence summary finding
    content.append(section_spacer())
    content.append(Paragraph(
        f"<b>Finding:</b> The file <i>{file_name}</i> has been cryptographically verified. "
        f"Its SHA-256 hash is recorded above and serves as the integrity reference for this certificate.",
        styles["body"]
    ))

    # ── SECTION 2: INTEGRITY FINDING ──────────────────────
    content.append(hr(styles))
    content.append(Paragraph("Section 2 — Integrity Finding", styles["h2"]))

    hash_at_upload = report.get("sha256", "—")
    integrity_rows = [
        ("Hash at Upload",               hash_at_upload),
        ("Hash at Certificate Generation", hash_at_upload),
        ("Comparison Result",            "MATCH — File integrity confirmed"),
    ]
    content.append(build_metadata_table(integrity_rows))
    content.append(section_spacer())

    content.append(Paragraph(
        "SHA-256 is a cryptographic hash function that produces a unique 64-character "
        "fingerprint for any digital file. If even a single byte of the file is changed, "
        "the SHA-256 value changes entirely. By comparing the hash recorded at upload to the "
        "hash computed at certificate generation, Evidentix can establish that the file has "
        "not been altered within the platform.",
        styles["body"]
    ))
    content.append(section_spacer())

    # C2PA status
    c2pa = report.get("c2pa", {})

    content.append(Paragraph(
        "Scope: This finding establishes integrity from the time of upload to Evidentix forward. "
        "It does not address the file's history, origin, or authenticity prior to upload.",
        styles["disclaimer"]
    ))

    # ── SECTION 3: CAPTURED METADATA ──────────────────────
    content.append(hr(styles))
    content.append(Paragraph("Section 3 — Captured Metadata", styles["h2"]))

    exif = report.get("exif") or {}
    exif_present = bool(exif) and "error" not in exif

    if exif_present:
        content.append(Paragraph(
            "The following metadata was read from the file as submitted. Metadata reflects "
            "values embedded in the file and is not independently validated by Evidentix.",
            styles["body"]
        ))

        meta_rows = []
        if exif.get("Make"):
            meta_rows.append(("Camera Make", exif["Make"]))
        if exif.get("Model"):
            meta_rows.append(("Device", exif["Model"]))
        if exif.get("DateTimeOriginal"):
            meta_rows.append(("Date Taken", exif["DateTimeOriginal"]))

        _lens_bits = []
        if exif.get("FNumber"):
            _lens_bits.append(f"f/{exif['FNumber']}")
        if exif.get("ExposureTime"):
            _lens_bits.append(f"{exif['ExposureTime']}s")
        if exif.get("ISOSpeedRatings"):
            _lens_bits.append(f"ISO {exif['ISOSpeedRatings']}")
        if exif.get("FocalLength"):
            _lens_bits.append(f"{exif['FocalLength']}mm")
        if _lens_bits:
            meta_rows.append(("Lens / Exposure", "  ".join(_lens_bits)))

        _gps = report.get("gps_coords")
        if _gps:
            _lat, _lon = _gps
            meta_rows.append(("GPS Coordinates", f"{_lat:.6f}, {_lon:.6f}"))
            _place = reverse_geocode(_lat, _lon)
            if _place:
                meta_rows.append(("Place Name", _place))

        if meta_rows:
            content.append(build_metadata_table(meta_rows))
            content.append(section_spacer())

        if _gps:
            _map_path = render_map_png(_lat, _lon)
            if _map_path:
                _map_block = [
                    Paragraph("<b>3a — Embedded Location Map</b>", styles["body"]),
                    Image(_map_path, width=4.5 * inch, height=3.375 * inch),
                    Paragraph(
                        "Map shows the GPS coordinates embedded in the file metadata. Embedded "
                        "coordinates reflect the capturing device's reported location at the time "
                        "of capture and may be subject to GPS error, signal degradation, or "
                        "post-capture manipulation. This certificate does not validate the "
                        "authenticity of embedded GPS data. Map data © OpenStreetMap contributors.",
                        styles["disclaimer"]
                    ),
                ]
                content.append(KeepTogether(_map_block))
                content.append(section_spacer())

        content.append(Paragraph(
            "Scope: EXIF metadata can be edited, stripped, or fabricated by ordinary software. "
            "Evidentix reports the metadata present in the file as submitted and does not certify "
            "its accuracy. The absence of metadata is not evidence of manipulation; many "
            "legitimate workflows remove it.",
            styles["disclaimer"]
        ))
    else:
        content.append(Paragraph(
            "No embedded capture metadata was found in this file. The absence of metadata is not "
            "evidence of manipulation; many legitimate workflows — screenshots, exports, and "
            "messaging applications — remove it during processing or transmission.",
            styles["disclaimer"]
        ))
    content.append(section_spacer())

    # ── SECTION 4: CONTENT CREDENTIALS (C2PA) ────────────────
    c2pa_state = c2pa.get("state", "ABSENT")
    c2pa_has_manifest = c2pa_state in ("VALID", "INVALID")

    content.append(hr(styles))
    # Section 4 opening flowables: staged so unsigned files can keep the whole
    # short section together; signed files append immediately (too tall to unify).
    state_label = c2pa.get("state_label", "No Content Credentials Detected")
    _s4_head = [
        Paragraph("Section 4 — Content Credentials (C2PA) Analysis", styles["h2"]),
        Paragraph(f"<b>Result: {state_label}</b>", styles["body"]),
    ]
    if c2pa_has_manifest:
        for _f in _s4_head:
            content.append(_f)
        content.append(section_spacer())

    if c2pa_has_manifest:
        # 4a — Manifest Summary
        content.append(Paragraph("<b>4a — Manifest Summary</b>", styles["body"]))
        manifest_rows = [
            ("Claim Generator",   c2pa.get("claim_generator") or "—"),
            ("Generator Version", c2pa.get("claim_generator_version") or "—"),
            ("Signing Time",      c2pa.get("signature_time") or "—"),
            ("Signing Issuer",    c2pa.get("signature_issuer") or "—"),
            ("Total Assertions",  str(c2pa.get("num_assertions", "—"))),
            ("Ingredients",       str(c2pa.get("num_ingredients", "—"))),
        ]
        content.append(build_metadata_table(manifest_rows))
        content.append(section_spacer())

        # 4b — Trust & Signature Validation
        content.append(Paragraph("<b>4b — Trust & Signature Validation</b>", styles["body"]))
        sig_valid = c2pa.get("signature_valid")
        trust_rows = [
            ("Signature Valid",   "Yes" if sig_valid is True else "No" if sig_valid is False else "Unknown"),
            ("Trust List Status", c2pa.get("trust_list_status") or "—"),
            ("Revocation Status", c2pa.get("revocation_status") or "—"),
        ]
        content.append(build_metadata_table(trust_rows))
        content.append(section_spacer())

        # 4c — AI & Content Assertions
        content.append(Paragraph("<b>4c — AI & Content Assertions</b>", styles["body"]))
        ai_rows = [
            ("AI Generated",      "YES — See findings below" if c2pa.get("has_ai_generation") else "Not detected"),
            ("AI Modified",       "YES — See findings below" if c2pa.get("has_ai_modification") else "Not detected"),
            ("AI Agents Found",   ", ".join(c2pa.get("ai_agents_found", [])) or "None"),
            ("Training/Mining",   "Present" if c2pa.get("has_training_mining") else "Not present"),
        ]
        content.append(build_metadata_table(ai_rows))
        content.append(section_spacer())

    # 4d — Plain English Findings (always shown)
    _summary_block = [
        Paragraph(f"<b>{'4d — ' if c2pa_has_manifest else ''}Expert Summary</b>", styles["body"]),
        Paragraph(
            c2pa.get("plain_english", "Content Credentials analysis not available."),
            styles["body"]
        ),
    ]
    if c2pa_has_manifest:
        content.append(KeepTogether(_summary_block))
    else:
        # Unsigned: keep heading + Result + Expert Summary as one unit
        content.append(KeepTogether(_s4_head + _summary_block))
    content.append(section_spacer())

    content.append(Paragraph(
        "Content Credentials (C2PA) is an open technical standard developed by Adobe, Microsoft, "
        "the BBC, and others to embed tamper-evident provenance data into digital files. "
        "Verification confirms the embedded record is cryptographically intact; it does not "
        "independently confirm the accuracy of the events or content depicted.",
        styles["disclaimer"]
    ))

    # ── SECTION 5: STRUCTURAL FINGERPRINT ──────
    content.append(hr(styles))
    content.append(Paragraph("Section 5 — Structural Fingerprint", styles["h2"]))

    _phash = report.get("phash")
    if _phash:
        content.append(build_metadata_table([
            ("Perceptual Hash (pHash)", str(_phash)),
        ]))
        content.append(section_spacer())
        content.append(Paragraph(
            "A perceptual hash is a compact fingerprint derived from the visual structure of an "
            "image rather than its raw bytes. Unlike the SHA-256 value in Section 2, which changes "
            "completely if a single byte is altered, a perceptual hash remains stable across minor "
            "re-encoding and reflects the image's visual content.",
            styles["body"]
        ))
        content.append(Paragraph(
            "Scope: This certificate records the perceptual hash as a forensic property of the file. "
            "It does not compare the file against any external database and makes no representation "
            "regarding the existence, identity, or content of any other file.",
            styles["disclaimer"]
        ))
    else:
        content.append(Paragraph(
            "A perceptual hash could not be derived for this file. This does not indicate "
            "manipulation; perceptual hashing applies to supported image formats and may be "
            "unavailable for other file types.",
            styles["disclaimer"]
        ))
    content.append(section_spacer())

    # ── SECTION 7: METHODOLOGY & LIMITATIONS ──────
    content.append(hr(styles))
    content.append(Paragraph("Section 7 — Methodology & Limitations", styles["h2"]))
    content.append(Paragraph(
        "<b>Methodology.</b> The submitted file was analyzed using a combination of forensic "
        "techniques, including SHA-256 hashing for file integrity verification, perceptual hashing "
        "to derive a structural fingerprint, metadata and EXIF extraction, and Content Credentials "
        "(C2PA) verification where present.",
        styles["body"]
    ))
    content.append(Paragraph(
        "<b>Limitations.</b> This certificate reflects a tool-assisted forensic analysis of the "
        "submitted file. It does not independently establish authorship, ownership, or legal "
        "infringement. Metadata may be altered or removed during processing or transmission. "
        "Conclusions are limited to the observable characteristics of the file analyzed.",
        styles["disclaimer"]
    ))
    content.append(section_spacer())

    content.append(Paragraph(
        "© 2026 Evidence Analyzer, LLC. All rights reserved. This record is generated by Evidentix™ and is protected by applicable copyright and intellectual property laws.",
        styles["disclaimer"]
    ))
    content.append(section_spacer())
    
# ── BUILD & RETURN ────────────────────────────────────
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp_path = tmp.name
    try:
        build_document(tmp_path, content, title=f"Evidentix Integrity Certificate")
        with open(tmp_path, "rb") as f:
            pdf_bytes = f.read()
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
    return certificate_id, pdf_bytes
