import io
import os
import tempfile
import uuid
from datetime import datetime, timezone

import qrcode
from reportlab.lib.units import inch
from reportlab.platypus import Image, Paragraph, Spacer, Table, TableStyle

from app.pdf_base import (
    DARK, GREY_LINE, PURPLE, PURPLE_BG, WHITE,
    build_document, build_metadata_table, build_styles, hr, section_spacer,
)


# =========================================================
# HELPERS
# =========================================================

def _redact_email(email: str) -> str:
    """k***@caldwell-law-firm.com"""
    if not email or "@" not in email:
        return email or "—"
    local, domain = email.split("@", 1)
    return f"{local[0]}***@{domain}"


def _fmt_bytes(size_bytes) -> str:
    try:
        b = int(size_bytes)
        if b < 1024:
            return f"{b} bytes"
        elif b < 1024 ** 2:
            return f"{b / 1024:.1f} KB"
        else:
            return f"{b / 1024 ** 2:.1f} MB"
    except Exception:
        return str(size_bytes)


def _generate_qr(url: str) -> Image:
    qr = qrcode.QRCode(box_size=4, border=2)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return Image(buf, width=1.2 * inch, height=1.2 * inch)


# =========================================================
# MAIN GENERATOR
# =========================================================

def generate_integrity_certificate(
    report: dict,
    case_id: str,
    evidence_id: str,
    generated_by: str,
    base_url: str = "https://evidenceanalyzer.com",
    chain_verified: bool = None,
) -> tuple:
    """
    Generates the Integrity Certificate PDF.

    Returns:
        (certificate_id, pdf_bytes)
        certificate_id: UUID v4 string
        pdf_bytes: bytes of the generated PDF
    """
    certificate_id = str(uuid.uuid4())
    generated_at = datetime.now(timezone.utc)
    generated_at_str = generated_at.strftime("%B %d, %Y at %H:%M:%S UTC")
    verify_url = f"{base_url}/verify/{certificate_id}"

    styles = build_styles()
    content = []

    # ── SECTION 1: HEADER ─────────────────────────────────
    content.append(Paragraph("Integrity Certificate", styles["title"]))
    content.append(Paragraph("Cryptographic Verification of File Integrity", styles["subtitle"]))
    content.append(hr(styles))

    header_rows = [
        ("Generated By",    "Evidentix"),
        ("Generated At",    generated_at_str),
        ("Certificate ID",  certificate_id),
        ("For use in",      "______________________________________"),
    ]
    content.append(build_metadata_table(header_rows))
    content.append(section_spacer())

    # File metadata table
    file_name   = report.get("file_name", "—")
    file_size   = _fmt_bytes(report.get("file_size"))
    mime_type   = report.get("metadata", {}).get("mime_type") or report.get("metadata", {}).get("format") or "—"
    upload_date = report.get("analysis_date", "—")
    sha256      = report.get("sha256", "—")
    redacted_user = _redact_email(generated_by)

    file_rows = [
        ("File Name",       file_name),
        ("File Size",       file_size),
        ("File Type",       mime_type),
        ("Upload Date",     upload_date),
        ("Uploading User",  redacted_user),
        ("SHA-256 Hash",    sha256),
    ]
    content.append(Paragraph("File Information", styles["h2"]))
    content.append(build_metadata_table(file_rows))

    # One-sentence summary finding
    content.append(section_spacer())
    content.append(Paragraph(
        f"<b>Finding:</b> The file <i>{file_name}</i> has been cryptographically verified. "
        f"Its SHA-256 hash is recorded above and serves as the integrity reference for this certificate.",
        styles["body"]
    ))

    # ── SECTION 2: INTEGRITY FINDING ──────────────────────
    content.append(hr(styles))
    content.append(Paragraph("Section 2 — Integrity Finding", styles["h2"]))

    hash_at_upload = report.get("sha256", "—")
    integrity_rows = [
        ("Hash at Upload",               hash_at_upload),
        ("Hash at Certificate Generation", hash_at_upload),
        ("Comparison Result",            "MATCH — File integrity confirmed"),
    ]
    content.append(build_metadata_table(integrity_rows))
    content.append(section_spacer())

    content.append(Paragraph(
        "SHA-256 is a cryptographic hash function that produces a unique 64-character "
        "fingerprint for any digital file. If even a single byte of the file is changed, "
        "the SHA-256 value changes entirely. By comparing the hash recorded at upload to the "
        "hash computed at certificate generation, Evidentix can establish that the file has "
        "not been altered within the platform.",
        styles["body"]
    ))
    content.append(section_spacer())

    # C2PA status
    c2pa = report.get("c2pa", {})
    c2pa_present = c2pa.get("present", False)

    if not c2pa_present:
        content.append(Paragraph(
            "No C2PA Content Credentials were present in the submitted file.",
            styles["disclaimer"]
        ))
    else:
        content.append(Paragraph(
            "C2PA Content Credentials detected. See Section 3 for full findings.",
            styles["body"]
        ))

    content.append(Paragraph(
        "Scope: This finding establishes integrity from the time of upload to Evidentix forward. "
        "It does not address the file's history, origin, or authenticity prior to upload.",
        styles["disclaimer"]
    ))

# ── SECTION 3: C2PA ───────────────────────────────────
    c2pa_state = c2pa.get("state", "ABSENT")
    c2pa_has_manifest = c2pa_state in ("VALID", "INVALID")

    content.append(hr(styles))
    content.append(Paragraph("Section 3 — Content Credentials (C2PA) Analysis", styles["h2"]))

    # State banner
    state_label = c2pa.get("state_label", "No Content Credentials Detected")
    content.append(Paragraph(f"<b>Result: {state_label}</b>", styles["body"]))
    content.append(section_spacer())

    if c2pa_has_manifest:
        # 3a — Manifest Summary
        content.append(Paragraph("<b>3a — Manifest Summary</b>", styles["body"]))
        manifest_rows = [
            ("Claim Generator",   c2pa.get("claim_generator") or "—"),
            ("Generator Version", c2pa.get("claim_generator_version") or "—"),
            ("Signing Time",      c2pa.get("signature_time") or "—"),
            ("Signing Issuer",    c2pa.get("signature_issuer") or "—"),
            ("Total Assertions",  str(c2pa.get("num_assertions", "—"))),
            ("Ingredients",       str(c2pa.get("num_ingredients", "—"))),
        ]
        content.append(build_metadata_table(manifest_rows))
        content.append(section_spacer())

        # 3b — Trust & Signature Validation
        content.append(Paragraph("<b>3b — Trust & Signature Validation</b>", styles["body"]))
        sig_valid = c2pa.get("signature_valid")
        trust_rows = [
            ("Signature Valid",   "Yes" if sig_valid is True else "No" if sig_valid is False else "Unknown"),
            ("Trust List Status", c2pa.get("trust_list_status") or "—"),
            ("Revocation Status", c2pa.get("revocation_status") or "—"),
        ]
        content.append(build_metadata_table(trust_rows))
        content.append(section_spacer())

        # 3c — AI & Content Assertions
        content.append(Paragraph("<b>3c — AI & Content Assertions</b>", styles["body"]))
        ai_rows = [
            ("AI Generated",      "YES — See findings below" if c2pa.get("has_ai_generation") else "Not detected"),
            ("AI Modified",       "YES — See findings below" if c2pa.get("has_ai_modification") else "Not detected"),
            ("AI Agents Found",   ", ".join(c2pa.get("ai_agents_found", [])) or "None"),
            ("Training/Mining",   "Present" if c2pa.get("has_training_mining") else "Not present"),
        ]
        content.append(build_metadata_table(ai_rows))
        content.append(section_spacer())

    # 3d — Plain English Findings (always shown)
    content.append(Paragraph("<b>3d — Expert Summary</b>", styles["body"]))
    content.append(Paragraph(
        c2pa.get("plain_english", "Content Credentials analysis not available."),
        styles["body"]
    ))
    content.append(section_spacer())

    content.append(Paragraph(
        "Content Credentials (C2PA) is an open technical standard developed by Adobe, Microsoft, "
        "the BBC, and others to embed tamper-evident provenance data into digital files. "
        "Verification confirms the embedded record is cryptographically intact; it does not "
        "independently confirm the accuracy of the events or content depicted.",
        styles["disclaimer"]
    ))
# ── BUILD & RETURN ────────────────────────────────────
    import tempfile, os
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp_path = tmp.name
    build_document(tmp_path, content, title=f"Evidentix Integrity Certificate")
    with open(tmp_path, "rb") as f:
        pdf_bytes = f.read()
    os.unlink(tmp_path)
    return certificate_id, pdf_bytes
