import io
import os
import tempfile
import uuid
from datetime import datetime, timezone

import qrcode
from reportlab.lib.units import inch
from reportlab.platypus import Image, KeepTogether, Paragraph, Spacer, Table, TableStyle

from app.pdf_base import (
    DARK, GREY_LINE, PURPLE, PURPLE_BG, WHITE,
    build_document, build_metadata_table, build_styles, hr, section_spacer,
)
from app.utils.map_render import render_map_png
from app.utils.geocode import reverse_geocode
from app.utils.integrity import verify_integrity


# =========================================================
# HELPERS
# =========================================================

def _redact_email(email: str) -> str:
    """k***@caldwell-law-firm.com"""
    if not email or "@" not in email:
        return email or "—"
    local, domain = email.split("@", 1)
    return f"{local[0]}***@{domain}"


def _fmt_exposure(value):
    """Format EXIF ExposureTime as a conventional shutter-speed string."""
    if not value:
        return "—"
    # Already a fraction string like "1/4115" — keep as-is
    s = str(value).strip()
    if "/" in s:
        return f"{s}s"
    try:
        x = float(value)
    except (TypeError, ValueError):
        return f"{s}s"
    if x <= 0:
        return f"{s}s"
    if x >= 1:
        # Long exposure: show as seconds, trim trailing zeros
        return f"{x:.1f}".rstrip("0").rstrip(".") + "s"
    # Fast shutter: convert to 1/N
    denom = round(1 / x)
    return f"1/{denom}s"


def _fmt_bytes(size_bytes) -> str:
    try:
        b = int(size_bytes)
        if b < 1024:
            return f"{b} bytes"
        elif b < 1024 ** 2:
            return f"{b / 1024:.1f} KB"
        else:
            return f"{b / 1024 ** 2:.1f} MB"
    except Exception:
        return str(size_bytes)


def _generate_qr(url: str) -> Image:
    qr = qrcode.QRCode(box_size=4, border=2)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return Image(buf, width=1.2 * inch, height=1.2 * inch)


# =========================================================
# MAIN GENERATOR
# =========================================================

def generate_integrity_certificate(
    report: dict,
    case_id: str,
    evidence_id: str,
    generated_by: str,
    base_url: str = "https://evidenceanalyzer.com",
    chain_verified: bool = None,
    file_key: str = None,
) -> tuple:
    """
    Generates the Integrity Certificate PDF.

    Returns:
        (certificate_id, pdf_bytes)
        certificate_id: UUID v4 string
        pdf_bytes: bytes of the generated PDF
    """
    certificate_id = str(uuid.uuid4())
    generated_at = datetime.now(timezone.utc)
    generated_at_str = generated_at.strftime("%B %d, %Y at %H:%M:%S UTC")
    verify_url = f"{base_url}/verify/{certificate_id}"

    styles = build_styles()
    content = []
    _temp_files = []

    # ── SECTION 1: HEADER ─────────────────────────────────
    content.append(Paragraph("Evidentix\u2122 Integrity Certificate", styles["title"]))
    content.append(Paragraph("Cryptographic Verification of File Integrity", styles["subtitle"]))
    content.append(hr(styles))

    header_rows = [
        ("Generated By",    "Evidentix\u2122 | Evidence Analyzer, LLC"),
        ("Generated",       generated_at_str),
        ("Certificate ID",  certificate_id),
        ("For use in",      f"Case {case_id}"),
  
    ]
    content.append(build_metadata_table(header_rows))
    content.append(section_spacer())

    # File metadata table
    file_name   = report.get("file_name", "—")
    file_size   = _fmt_bytes(report.get("file_size"))
    mime_type   = report.get("metadata", {}).get("mime_type") or report.get("metadata", {}).get("format") or "—"
    upload_date = report.get("analysis_date", "—")
    sha256      = report.get("sha256", "—")
    redacted_user = _redact_email(generated_by)

    file_rows = [
        ("File Name",       file_name),
        ("File Size",       file_size),
        ("File Type",       mime_type),
        ("Upload Date",     upload_date),
        ("Uploading User",  redacted_user),
        ("SHA-256 Hash",    sha256),
    ]
    content.append(Paragraph("File Information", styles["h2"]))
    content.append(build_metadata_table(file_rows))

    content.append(section_spacer())
    content.append(Paragraph(
        "This certificate documents the technical characteristics of the file identified above "
        "as received and stored by Evidentix on the date shown. It does not establish the truth, "
        "origin, authorship, or completeness of the file's contents, nor does it constitute a "
        "determination of the file's admissibility in any proceeding. Admissibility is determined "
        "by the court under the applicable rules of evidence.",
        styles["disclaimer"]
    ))

    # One-sentence summary finding
    content.append(section_spacer())
    content.append(Paragraph(
        "<b>Finding:</b> A SHA-256 cryptographic hash of the file identified above was recorded "
        "at upload and is shown above as the integrity reference for this certificate. "
        "Re-verification of file integrity is reported in Section 2.",
        styles["body"]
    ))

    # ── SECTION 2: INTEGRITY FINDING ──────────────────────
    content.append(hr(styles))
    content.append(Paragraph("Section 2 — Integrity Finding", styles["h2"]))

    hash_at_upload = report.get("sha256", "—")
    verification = verify_integrity(hash_at_upload, file_key)
    recomputed = verification["recomputed"]
    match = verification["match"]

    if match is True:
        integrity_rows = [
            ("Hash at Upload",          hash_at_upload),
            ("Hash at Re-Verification", recomputed),
            ("Result",
             "VERIFIED — file re-read from storage and hash recomputed; recomputed hash "
             "matches the hash recorded at upload, indicating the file has not been altered "
             "while in Evidentix's custody."),
        ]
    elif match is False:
        integrity_rows = [
            ("Hash at Upload",          hash_at_upload),
            ("Hash at Re-Verification", recomputed),
            ("Result",
             "DISCREPANCY DETECTED — the hash recomputed from storage does not match the hash "
             "recorded at upload. This indicates the stored file differs from the file as "
             "originally received and should be investigated before reliance."),
        ]
    else:
        integrity_rows = [
            ("Hash at Upload",          hash_at_upload),
            ("Result",
             "NOT RE-VERIFIED — the file could not be re-read from storage at the time of "
             "generation, so its hash was not recomputed. The hash recorded at upload is shown "
             "above as the integrity reference; no current comparison was performed."),
        ]
    content.append(build_metadata_table(integrity_rows))
    content.append(section_spacer())

    content.append(Paragraph(
        "SHA-256 is a cryptographic hash function that produces a unique 64-character "
        "fingerprint for any digital file. If even a single byte of the file is changed, "
        "the SHA-256 value changes entirely. By comparing the hash recorded at upload to the "
        "hash computed at certificate generation, Evidentix can establish that the file has "
        "not been altered within the platform. "
        "SHA-256 is a published, generally accepted cryptographic standard (FIPS 180-4) with "
        "no known practical collision.",
        styles["body"]
    ))
    content.append(section_spacer())

    # C2PA status
    c2pa = report.get("c2pa", {})

    content.append(Paragraph(
        "Scope: This finding establishes integrity from the time of upload to Evidentix forward. "
        "It does not address the file's history, origin, or authenticity prior to upload.",
        styles["disclaimer"]
    ))

    # ── SECTION 3: CAPTURED METADATA ──────────────────────
    content.append(hr(styles))
    content.append(Paragraph("Section 3 — Captured Metadata", styles["h2"]))

    exif = report.get("exif") or {}
    exif_present = bool(exif) and "error" not in exif

    if exif_present:
        content.append(Paragraph(
            "The following metadata was read from the file as submitted. Metadata reflects "
            "values embedded in the file and is not independently validated by Evidentix.",
            styles["body"]
        ))

        meta_rows = []
        if exif.get("Make"):
            meta_rows.append(("Camera Make", exif["Make"]))
        if exif.get("Model"):
            meta_rows.append(("Device", exif["Model"]))
        if exif.get("DateTimeOriginal"):
            meta_rows.append(("Date Taken", exif["DateTimeOriginal"]))

        _lens_bits = []
        if exif.get("FNumber"):
            _lens_bits.append(f"f/{exif['FNumber']}")
        if exif.get("ExposureTime"):
            _lens_bits.append(_fmt_exposure(exif["ExposureTime"]))
        if exif.get("ISOSpeedRatings"):
            _lens_bits.append(f"ISO {exif['ISOSpeedRatings']}")
        if exif.get("FocalLength"):
            _lens_bits.append(f"{exif['FocalLength']}mm")
        if _lens_bits:
            meta_rows.append(("Lens / Exposure", "  ".join(_lens_bits)))

        _gps = report.get("gps_coords")
        if _gps:
            _lat, _lon = _gps
            meta_rows.append(("GPS Coordinates", f"{_lat:.6f}, {_lon:.6f}"))
            _place = reverse_geocode(_lat, _lon)
            if _place:
                meta_rows.append(("Place Name", _place))

        if meta_rows:
            content.append(build_metadata_table(meta_rows))
            content.append(section_spacer())

        if _gps:
            _map_path = render_map_png(_lat, _lon)
            if _map_path:
                _temp_files.append(_map_path)
                _map_block = [
                    Paragraph("<b>3a — Embedded Location Map</b>", styles["body"]),
                    Image(_map_path, width=4.5 * inch, height=3.375 * inch),
                    Paragraph(
                        "Map shows the GPS coordinates embedded in the file metadata. Embedded "
                        "coordinates reflect the capturing device's reported location at the time "
                        "of capture and may be subject to GPS error, signal degradation, or "
                        "post-capture manipulation. This certificate does not validate the "
                        "authenticity of embedded GPS data. Map data © OpenStreetMap contributors.",
                        styles["disclaimer"]
                    ),
                ]
                content.append(KeepTogether(_map_block))
                content.append(section_spacer())

        content.append(Paragraph(
            "Scope: EXIF metadata can be edited, stripped, or fabricated by ordinary software. "
            "Evidentix reports the metadata present in the file as submitted and does not certify "
            "its accuracy. The absence of metadata is not evidence of manipulation; many "
            "legitimate workflows remove it.",
            styles["disclaimer"]
        ))
    else:
        content.append(Paragraph(
            "No embedded capture metadata was found in this file. The absence of metadata is not "
            "evidence of manipulation; many legitimate workflows — screenshots, exports, and "
            "messaging applications — remove it during processing or transmission.",
            styles["disclaimer"]
        ))
    content.append(section_spacer())

    # ── SECTION 4: CHAIN OF CUSTODY ──────
    content.append(hr(styles))
    content.append(Paragraph("Section 4 — Chain of Custody", styles["h2"]))
    if chain_verified is True:
        content.append(Paragraph(
            "Result: CHAIN INTACT — The Evidentix custody log associated with this file is "
            "recorded as a cryptographic hash chain, in which each recorded event is bound to the "
            "one before it. As of certificate generation, that chain was verified and no alteration "
            "of the recorded custody events was detected. This reflects the integrity of custody "
            "events recorded within Evidentix and does not address the file's handling before it "
            "was received by Evidentix.",
            styles["body"]
        ))
        content.append(Paragraph(
            "A complete, event-by-event custody record is available as a separate Evidentix "
            "Custody Record.",
            styles["disclaimer"]
        ))
    elif chain_verified is False:
        content.append(Paragraph(
            "Result: CHAIN DISCREPANCY DETECTED — Verification of the Evidentix custody log "
            "associated with this file detected a discrepancy in the hash chain, indicating that "
            "one or more recorded custody events may have been altered after recording. This "
            "finding should be investigated and disclosed before the custody record is relied "
            "upon. A complete Evidentix Custody Record should be reviewed.",
            styles["body"]
        ))
    else:
        content.append(Paragraph(
            "Result: NOT VERIFIED — Chain integrity was not verified at the time this certificate "
            "was generated. Evidentix maintains custody events as a cryptographic hash chain; a "
            "complete Evidentix Custody Record, including chain verification, is available "
            "separately.",
            styles["body"]
        ))

    # ── SECTION 5: CONTENT ANALYSIS ──────
    content.append(hr(styles))
    content.append(Paragraph("Section 5 — Content Analysis", styles["h2"]))
    content.append(Paragraph(
        "The findings in this section describe content-level characteristics and indicators. "
        "They differ in kind from the cryptographic and custody findings above: some are reported "
        "by third-party software embedded in the file rather than determined by Evidentix, and the "
        "AI-related indicators are not independently verified. Read this section together with the "
        "limitations noted below.",
        styles["body"]
    ))

    # 5a — Structural Fingerprint (pHash): existing content, moved under the 5a label.
    _phash = report.get("phash")
    if _phash:
        _s5a_block = [
            Paragraph("<b>5a — Structural Fingerprint</b>", styles["body"]),
            build_metadata_table([
                ("Perceptual Hash (pHash)", str(_phash)),
            ]),
            section_spacer(),
            Paragraph(
                "A perceptual hash is a compact fingerprint derived from the visual structure of an "
                "image rather than its raw bytes. Unlike the SHA-256 value in Section 2, which changes "
                "completely if a single byte is altered, a perceptual hash remains stable across minor "
                "re-encoding and reflects the image's visual content.",
                styles["body"]
            ),
            Paragraph(
                "Scope: This certificate records the perceptual hash as a forensic property of the file. "
                "It does not compare the file against any external database and makes no representation "
                "regarding the existence, identity, or content of any other file.",
                styles["disclaimer"]
            ),
        ]
        content.append(KeepTogether(_s5a_block))
    else:
        content.append(Paragraph("<b>5a — Structural Fingerprint</b>", styles["body"]))
        content.append(Paragraph(
            "A perceptual hash could not be derived for this file. This does not indicate "
            "manipulation; perceptual hashing applies to supported image formats and may be "
            "unavailable for other file types.",
            styles["disclaimer"]
        ))
    content.append(section_spacer())

    # 5b / 5c — Content Credentials (C2PA): only when a manifest is present.
    _c2pa_state = c2pa.get("state", "ABSENT")
    # Manifest-bearing = any state except the no-manifest ones. Complement form
    # (not an explicit allow-list) so new manifest-present states — e.g.
    # SIGNED_UNRECOGNIZED_ISSUER — render §5b/§5c instead of falling through to
    # the no-manifest path.
    _c2pa_has_manifest = _c2pa_state not in ("ABSENT", "UNAVAILABLE")

    if _c2pa_has_manifest:
        # 5b — Manifest & Signature (DETERMINISTIC): standard "verified" tables.
        content.append(Paragraph(
            "<b>5b — Content Credentials (C2PA): Manifest &amp; Signature</b>", styles["body"]
        ))
        content.append(build_metadata_table([
            ("Claim Generator",   c2pa.get("claim_generator") or "—"),
            ("Generator Version", c2pa.get("claim_generator_version") or "—"),
            ("Signing Time",      c2pa.get("signature_time") or "—"),
            ("Signing Issuer",    c2pa.get("signature_issuer") or "—"),
            ("Total Assertions",  str(c2pa.get("num_assertions", "—"))),
            ("Ingredients",       str(c2pa.get("num_ingredients", "—"))),
        ]))
        content.append(section_spacer())
        _sig_valid = c2pa.get("signature_valid")
        content.append(build_metadata_table([
            ("Signature Valid",   "Yes" if _sig_valid is True else "No" if _sig_valid is False else "Unknown"),
            ("Trust List Status", c2pa.get("trust_list_status") or "—"),
            ("Revocation Status", c2pa.get("revocation_status") or "—"),
        ]))
        content.append(Paragraph(
            "The above reflects validation of the embedded C2PA manifest's cryptographic signature. "
            "A valid signature indicates the manifest's contents have not been altered since signing "
            "and were signed by the identified issuer. This is a deterministic cryptographic check.",
            styles["body"]
        ))
        content.append(section_spacer())

        # 5c — AI & Content Assertions (PROBABILISTIC): demarcated PURPLE callout box.
        # Hand-built table (NOT build_metadata_table) so it is visually distinct from
        # the verified tables above: solid PURPLE_BG fill + ~1.25pt PURPLE outer box +
        # a full-width caption row marking the contents as reported, not verified.
        # Widths [144, 324] == 2.0in / 4.5in, matching build_metadata_table's columns.
        _ai_rows = [
            [Paragraph(
                "<b>Reported by the file's embedded credentials — not verified by Evidentix</b>",
                styles["body"]
            ), ""],
            [Paragraph("AI Generation", styles["body"]),
             Paragraph("Asserted" if c2pa.get("has_ai_generation") else "Not asserted", styles["body"])],
            [Paragraph("AI Modification", styles["body"]),
             Paragraph("Asserted" if c2pa.get("has_ai_modification") else "Not asserted", styles["body"])],
            [Paragraph("AI Agents Named", styles["body"]),
             Paragraph(", ".join(c2pa.get("ai_agents_found", [])) or "None", styles["body"])],
            [Paragraph("Training/Mining", styles["body"]),
             Paragraph("Asserted" if c2pa.get("has_training_mining") else "Not asserted", styles["body"])],
        ]
        _ai_table = Table(_ai_rows, colWidths=[144, 324])
        _ai_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), PURPLE_BG),
            ("BOX", (0, 0), (-1, -1), 1.25, PURPLE),
            ("SPAN", (0, 0), (-1, 0)),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, PURPLE),
            ("INNERGRID", (0, 1), (-1, -1), 0.25, GREY_LINE),
            ("TEXTCOLOR", (0, 0), (-1, 0), DARK),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        content.append(KeepTogether([_ai_table]))
        content.append(hr(styles))
        content.append(Paragraph(
            "These assertions are recorded within the file's embedded data by the software that "
            "produced it; they are reports contained in the file, not findings made or verified by "
            "Evidentix. They have no established error rate. Offering them in a proceeding for the "
            "truth of the matter asserted would likely require expert testimony under Federal Rule of "
            "Evidence 702/707. Their presence or absence is not, by itself, a determination that the "
            "file is or is not AI-generated.",
            styles["disclaimer"]
        ))
        content.append(section_spacer())

    # Expert Summary (always shown — VALID/INVALID and ABSENT/UNAVAILABLE).
    content.append(Paragraph("<b>Expert Summary</b>", styles["body"]))
    content.append(Paragraph(
        c2pa.get("plain_english", "Content Credentials analysis not available."),
        styles["body"]
    ))
    content.append(section_spacer())

    # §5 closing disclaimer (always shown).
    content.append(Paragraph(
        "Content Credentials (C2PA) is an open technical standard for embedding provenance data into "
        "digital files. Signature validation confirms the embedded manifest is cryptographically "
        "intact and unaltered since signing; it does not confirm the accuracy of the events, content, "
        "or AI-related claims the manifest describes. The integrity of the manifest and the truth of "
        "its contents are distinct.",
        styles["disclaimer"]
    ))
    content.append(section_spacer())

    # ── SECTION 6: METHODOLOGY ──────
    content.append(hr(styles))
    content.append(Paragraph("Section 6 — Methodology", styles["h2"]))
    content.append(Paragraph(
        "<b>Methodology.</b> The submitted file was analyzed using a combination of forensic "
        "techniques, including SHA-256 hashing for file integrity verification, perceptual hashing "
        "to derive a structural fingerprint, metadata and EXIF extraction, and Content Credentials "
        "(C2PA) verification where present.",
        styles["body"]
    ))
    content.append(Paragraph(
        "SHA-256 re-verification is a deterministic, reproducible process: the stored file is "
        "re-read at the time of certificate generation and its hash recomputed from the raw bytes. "
        "Re-reading the same bytes always yields the same hash, so a match between the recomputed "
        "hash and the hash recorded at upload demonstrates the file is unchanged within Evidentix's "
        "custody. This reproducibility — a process that produces an accurate result — is described "
        "in Federal Rule of Evidence 901(b)(9). Whether an authentication foundation is established "
        "in any particular matter is a determination for the court under FRE 104.",
        styles["body"]
    ))
    content.append(section_spacer())

    # ── SECTION 7: LIMITATIONS & DISCLAIMERS ──────
    content.append(hr(styles))
    content.append(Paragraph("Section 7 — Limitations & Disclaimers", styles["h2"]))
    content.append(Paragraph(
        "<b>Limitations.</b> This certificate reflects a tool-assisted forensic analysis of the "
        "submitted file. It does not independently establish authorship, ownership, or legal "
        "infringement. Metadata may be altered or removed during processing or transmission. "
        "Conclusions are limited to the observable characteristics of the file analyzed.",
        styles["disclaimer"]
    ))
    content.append(Paragraph(
        "This certificate documents technical facts to support an authentication foundation under "
        "FRE 901; it does not itself determine admissibility, which is the court's role under "
        "FRE 104. Laying a courtroom foundation may require a witness with personal knowledge or a "
        "qualified expert, particularly for any probabilistic findings.",
        styles["disclaimer"]
    ))
    content.append(section_spacer())

    content.append(Paragraph(
        "© 2026 Evidence Analyzer, LLC. All rights reserved. This record is generated by Evidentix™ and is protected by applicable copyright and intellectual property laws.",
        styles["disclaimer"]
    ))
    content.append(section_spacer())
    
# ── BUILD & RETURN ────────────────────────────────────
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp_path = tmp.name
    try:
        build_document(tmp_path, content, title=f"Evidentix Integrity Certificate")
        with open(tmp_path, "rb") as f:
            pdf_bytes = f.read()
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        for _tf in _temp_files:
            try:
                os.unlink(_tf)
            except OSError:
                pass
    return certificate_id, pdf_bytes
